# CodeRabbit Configuration
# https://docs.coderabbit.ai/guides/configure-coderabbit

language: ko-KR

reviews:
  profile: assertive
  request_changes_workflow: false
  high_level_summary: true
  poem: true
  review_status: true
  collapse_walkthrough: false
  path_filters:
    - "docs/sprint-artifacts/**"  # 스프린트 문서는 리뷰 대상
    - "!**/docs/**"  # 나머지 docs 디렉토리 제외
    - "!**/*.md"  # 일반 마크다운 파일 제외
    - "!assets/modules/**"

  tools:
    clippy:
      enabled: true
    markdownlint:
      enabled: false  # 설계 문서 프로젝트 - 형식보다 내용 중심

  path_instructions:
    - path: "docs/sprint-artifacts/**/*.md"
      instructions: |
        스프린트 산출물 문서입니다.
        - 스프린트 목표와 성과 일치성 확인
        - 문서 구조 및 완성도 검토
        - 기술적 내용의 정확성 확인
        - 다음 스프린트 연계성 검토

    - path: "cad-engine/**/*.rs"
      instructions: |
        Rust WASM 엔진 코드입니다.
        - wasm-bindgen 패턴 준수 확인
        - 메모리 안전성 검토
        - JS 인터페이스 설계 검토
        - panic 가능성 확인

    - path: "**/*.mjs"
      instructions: |
        Node.js ESM 테스트 코드입니다.
        - WASM 모듈 로드 패턴 확인
        - 에러 핸들링 검토
        - NFR (성능 요구사항) 검증 로직 확인

chat:
  auto_reply: true
